"""modify Task Model

Revision ID: 4aecd08ce83c
Revises: f4179b90a1a4
Create Date: 2017-06-12 21:59:21.512232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aecd08ce83c'
down_revision = 'f4179b90a1a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_hwResource', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'task_hwResource')
    # ### end Alembic commands ###
