"""add data_treated_file_name attribute in Task Model to save the treated file

Revision ID: aaa9ac8649ee
Revises: 4aecd08ce83c
Create Date: 2017-06-16 19:39:06.989882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaa9ac8649ee'
down_revision = '4aecd08ce83c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('data_treated_file_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'data_treated_file_name')
    # ### end Alembic commands ###
